import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'course_model.mapper.dart';

@MappableClass()
class CourseModel with CourseModelMappable {
  final int id;
  final String tid;
  final String category;
  final String title;
  final String description;
  final double price;
  @MappableField(key: 'number_of_trainees')
  final int numberOfTrainees;
final String startDate; 
final String endDate;
  final String image;
  final String location;
  final String state;
  @MappableField(key: 'created_at')
  final String createdAt;

  CourseModel({
    required this.id,
    required this.tid,
    required this.category,
    required this.title,
    required this.description,
    required this.price,
    required this.numberOfTrainees,
    required this.startDate,
    required this.endDate,
    required this.image,
    required this.location,
    required this.state,
    required this.createdAt,
  });
}
