// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:makfoul_app/model/course/course_model.dart';
import 'package:makfoul_app/model/user/user_model.dart';

// Will be generated by dart_mappable
part 'order_model.mapper.dart';

@MappableClass()
class OrderModel with OrderModelMappable {
  final int id;

  @MappableField(key: 'created_at')
  final String createdAt;

  final UserModel uid;

  @MappableField(key: 'course_id')
  final CourseModel courseId;

  const OrderModel({
    required this.id,
    required this.createdAt,
    required this.uid,
    required this.courseId,
  });
}
