// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'user_model.mapper.dart';

@MappableClass()
class UserModel with UserModelMappable {
  String UID;
  String name;
  String role;
  String email;
  String phone;
  String? avatar;

  @MappableField(key: 'created_at')
  String createdAt;

  UserModel({
    required this.UID,
    required this.name,
    required this.role,
    required this.email,
    required this.phone,
    this.avatar,
    required this.createdAt,
  });
}
