// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'user_model.mapper.dart';

@MappableClass()
class UserModel with UserModelMappable {
  final String UID;
  final String name;
  final String role;
  final String email;
  final String phone;
  final String avatar;

  @MappableField(key: 'created_at')
  final String createdAt;

  const UserModel({
    required this.UID,
    required this.name,
    required this.role,
    required this.email,
    required this.phone,
    required this.avatar,
    required this.createdAt,
  });
}
